# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_training.ipynb (unless otherwise specified).

__all__ = ['AverageMeter']

# Cell
import torch
import torch.nn as nn

# Cell
class AverageMeter:

    def __init__(self, store_vals=False, store_avgs=False):
        self.store_vals = store_vals
        self.store_avgs = store_avgs
        if store_vals: self.values = []
        if store_avgs: self.avgs = []
        self.sum, self.n, self.avg = 0, 0, 0

    def update(self, v):
        if self.store_vals: self.values.append(v)
        self.n += 1
        self.avg += (v - self.avg)/self.n

    def reset(self):
        if self.store_avgs and self.avg: self.avgs.append(self.avg)
        self.sum, self.n, self.avg = 0, 0, 0